;-----------------------------------------------------------------------
include     windows.inc

include     user32.inc
include     kernel32.inc

includelib  user32.lib
includelib  kernel32.lib

include     masm32.inc
includelib  masm32.lib

include     macros.asm

include     b64.inc
includelib  b64.core.lib
;-----------------------------------------------------------------------
